spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:duck-db.cjwea4q0q833.us-east-1.rds.amazonaws.com}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:korol_iot_14}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:rootroot}
  jpa:
    #Show or not log for each sql query
    show-sql: true
    hibernate:
      #Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#    mvc: #the fix for swagger
#      pathmatch:
#        matching-strategy: ant_path_matcher

server:
  port: 8800
